### PR TITLE
feat: providing a option to disable delete confirmtion

### PR DESCRIPTION
**Pull request by gh-liu**
#1

### CODE REVIEW

**Comment by hachy** [comment]
Thank you for PR. It looks nice.
But it's easy to get confused when pressing `D` imo.
That's the reason I added the confirmation.
So it would be nice to have a message after deleting.

**Review by hachy — COMMENTED** [review]
Thank you for PR. It looks nice.
But it's easy to get confused when pressing `D` imo.
That's the reason I added the confirmation.
So it would be nice to have a message after deleting.

**Review by hachy — CHANGES_REQUESTED** [review]
Using `vim.api.nvim_notify` or something like that.

**Comment by gh-liu** [comment]
already added [028688a](https://github.com/hachy/cmdpalette.nvim/pull/2/commits/028688ac76911861f849ed6f1adc94ce7dc3bb38)

**Review by hachy — APPROVED** [review]
Looks great! Thank you 🎉

**Pull request merged**
